import Link from "next/link";
import { ListItems } from "./components";
import "./globals.css";
import type { Metadata } from "next";
import { Suspense } from "react";
import ListSuspense from "./components/listSuspense";
import HeaderComponent from "./components/header";
import FooterComponent from "./components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const response = await fetch(
    `${process.env.TOP_STORIES}&limitToFirst=10&orderBy="$key"`
  );

  if (!response.ok) {
    return <div>Error loading data</div>;
  }

  const posts = (await response.json()) as number[];
  return (
    <html lang="en">
      <body className="grid grid-rows-[60px,1fr] h-screen">
        <HeaderComponent />
        <main className="grid grid-cols-[320px,1fr] gap-4">
          <aside>
            <ul className="mt-8">
              {posts.map((id) => (
                <Link href={`/${id}`} key={id}>
                  <Suspense fallback={<ListSuspense />}>
                    <ListItems id={id} />
                  </Suspense>
                </Link>
              ))}
            </ul>
          </aside>
          <section>{children}</section>
        </main>
        <FooterComponent />
      </body>
    </html>
  );
}
