import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="grid grid-rows-[60px,1fr] h-screen">
        <header className="bg-yellow-400 text-black font-semibold grid place-content-center">
          HackerNews Reader
        </header>
        <main className="grid grid-cols-[320px,1fr] gap-4">
          <aside>left bar</aside>
          <section>{children}</section>
        </main>
      </body>
    </html>
  );
}
